---
os: osx
language: objective-c
osx_image: xcode14.0
cache:
  bundler: true
  cocoapods: true
branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
  - OS_Version="16.0"
jobs:
  exclude:
    - env: LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail && xcodebuild -workspace AlphaWallet.xcworkspace -scheme AlphaWalletTests -destination platform\=iOS\ Simulator,OS\=$OS_Version,name\=iPhone\ 14 build test | xcpretty
...
